version: '3'
services:
  dbt:
    image: fishtownanalytics/dbt:1.0.0
    # build: . # This will build the Dockerfile in the current directory
    working_dir: /dbt
    volumes:
      - ./dbt_project:/dbt
    environment:
      DBT_PROFILES_DIR: /dbt
    env_file:
      - .env
