version: '3'
services:
  dbt:
    # image: fishtownanalytics/dbt:1.0.0
    build: .
    working_dir: /dbt
    entrypoint: ["/dbt/entrypoint.sh"]
    volumes:
      - ./dbt_project:/dbt
    environment:
      DBT_PROFILES_DIR: /dbt
    env_file:
      - .env
