
version: 2

sources:
  - name: leetcode
    database: leetcode
    schema: public
    tables:
      - name: accepted_rides_1635
      - name: accepted_rides_1645
      - name: accepted_rides_1651
      - name: accounts_1454
      - name: accounts_1843
      - name: accounts_1907
      - name: actions_1113
      - name: actions_1132
      - name: activities_1355
      - name: activities_1484
      - name: activity_1097
      - name: activity_1141
      - name: activity_1142
      - name: activity_1661
      - name: activity_511
      - name: activity_534
      - name: activity_550
      - name: activity_550_tc_2
      - name: actor_director_1050
      - name: address_175
      - name: ads_1322
      - name: ads_1809
      - name: amz
      - name: books_1098
      - name: boxes_1715
      - name: buses_2142
      - name: buses_2153
      - name: california_2072
      - name: calls_1501
      - name: calls_1699
      - name: calls_1972
      - name: bonus_577
      - name: candidate_574
      - name: candidates_2004
      - name: candidates_2004_tc_2
      - name: candidates_2010
      - name: candidates_2010_tc_2
      - name: candidates_2041
      - name: championships_1783
      - name: chargebacks_1205
      - name: chests_1715
      - name: cinema_603
      - name: cinema_620
      - name: coffee_shop_2388
      - name: company_607
      - name: confirmations_1934
      - name: confirmations_1939
      - name: contacts_1364
      - name: content_1495
      - name: contests_1811
      - name: countries_1294
      - name: country_1501
      - name: courses_596
      - name: customer_1045
      - name: customer_1321
      - name: customer_2372
      - name: customer_584
      - name: customers_1364
      - name: customers_1398
      - name: customers_1511
      - name: customers_1532
      - name: customers_1549
      - name: customers_1596
      - name: customers_1607
      - name: customers_1613
      - name: customers_1821
      - name: daily_sales_1693
      - name: data_2159
      - name: days_1853
      - name: delivery_1173
      - name: delivery_1174
      - name: department_1179
      - name: department_184
      - name: department_185
      - name: department_580
      - name: departments_1350
      - name: drivers_1635
      - name: drivers_1645
      - name: drivers_1651
      - name: emp_name
      - name: employee_1075
      - name: customers_183
      - name: employee_1077
      - name: employee_1303
      - name: employee_1378
      - name: employee_1789
      - name: employee_570
      - name: employee_184
      - name: employee_185
      - name: employee_569
      - name: employee_181
      - name: employee_579
      - name: employee_615
      - name: employee_uni_1378
      - name: employees_1270
      - name: employees_1731
      - name: employees_1741
      - name: employees_1873
      - name: employees_1875
      - name: employee_577
      - name: employees_1965
      - name: employees_1978
      - name: employees_2394
      - name: enrollments_1112
      - name: events_1126
      - name: exam_1988
      - name: examinations_1280
      - name: exams_1412
      - name: executed_1767
      - name: experiments_1990
      - name: expressions_1440
      - name: failed_1225
      - name: flights_2112
      - name: flights_2112_tc_2
      - name: follow_614
      - name: followers_1729
      - name: friend_request_597
      - name: friends_1355
      - name: friendship_1264
      - name: friendship_1892
      - name: friendship_1917
      - name: friendship_1919
      - name: friendship_1949
      - name: genders_2308
      - name: groups
      - name: insurance_585
      - name: invoice_1677
      - name: invoices_1364
      - name: items_1158
      - name: items_1159
      - name: items_1479
      - name: keywords_2199
      - name: likes_1264
      - name: likes_1892
      - name: listens_1917
      - name: listens_1919
      - name: log_info_1747
      - name: logins_1454
      - name: logins_1890
      - name: logs_1285
      - name: logs_180
      - name: logs_2394
      - name: matches_1194
      - name: matches_1212
      - name: matches_1841
      - name: matches_2173
      - name: matches_2173_tc_2
      - name: members_2051
      - name: movie_rating_1341
      - name: movies_1341
      - name: newyork_2072
      - name: npv_1421
      - name: number_619
      - name: number_619_tc_2
      - name: numbers_571
      - name: numbers_571_tc_2
      - name: olympic_2377
      - name: orders_1098
      - name: orders_1158
      - name: orders_1159
      - name: orders_1327
      - name: orders_1398
      - name: orders_1479
      - name: orders_1511
      - name: orders_1532
      - name: orders_1549
      - name: orders_1565
      - name: orders_1596
      - name: orders_1607
      - name: orders_2084
      - name: orders_2292
      - name: orders_586
      - name: orders_607
      - name: orders_details_1867
      - name: passengers_2142
      - name: passengers_2153
      - name: patients_1527
      - name: person_1501
      - name: person_175
      - name: person_182
      - name: person_196
      - name: person_196_ans
      - name: pivot_test
      - name: orders_183
      - name: pivot_test_rainfall
      - name: playback_1809
      - name: players_1194
      - name: players_1783
      - name: point_2d_612
      - name: point_613
      - name: points_1459
      - name: points_change_2175
      - name: posts_2199
      - name: prices_1251
      - name: problems_2026
      - name: product_1045
      - name: product_1068
      - name: product_1082
      - name: product_1384
      - name: product_1511
      - name: product_1677
      - name: product_2324
      - name: product_2329
      - name: products_1164
      - name: products_1327
      - name: products_1549
      - name: products_1571
      - name: products_1596
      - name: products_1757
      - name: products_1777
      - name: products_2252
      - name: products_2253
      - name: products_2362
      - name: project_1075
      - name: project_1077
      - name: purchases_2051
      - name: purchases_2205
      - name: purchases_2228
      - name: purchases_2230
      - name: purchases_2362
      - name: queries_1211
      - name: queries_1421
      - name: queue_1204
      - name: register_1633
      - name: relations_1951
      - name: removals_1132
      - name: request_accepted_597
      - name: request_accepted_602
      - name: rides_1407
      - name: rides_1635
      - name: rides_1645
      - name: rides_1651
      - name: rides_2238
      - name: rounds_2041
      - name: salaries_1468
      - name: salaries_1965
      - name: salary_615
      - name: salary_627
      - name: sales_1068
      - name: sales_1082
      - name: sales_1384
      - name: sales_1445
      - name: sales_1543
      - name: sales_2324
      - name: sales_2329
      - name: sales_2372
      - name: salesperson_2372
      - name: salesperson_607
      - name: school_1988
      - name: school_a_1623
      - name: school_b_1623
      - name: school_c_1623
      - name: scores_1308
      - name: seat_626
      - name: seller_1607
      - name: sessions_1435
      - name: signups_1934
      - name: signups_1939
      - name: spending_1127
      - name: stadium_601
      - name: stocks_1393
      - name: store_2082
      - name: streams_2020
      - name: student_580
      - name: student_618
      - name: students_1280
      - name: students_1350
      - name: students_1412
      - name: students_2346
      - name: subjects_1280
      - name: submissions_1241
      - name: subscriptions_2020
      - name: succeeded_1225
      - name: surveylog_578
      - name: tasks_1767
      - name: tasks_2298
      - name: teacher_2356
      - name: team_points_2175
      - name: teams_1212
      - name: teams_1841
      - name: teams_2339
      - name: terms_2118
      - name: terms_2118_tc_2
      - name: terms_2118_tc_3
      - name: traffic_1107
      - name: transactions_1193
      - name: transactions_1205
      - name: transactions_1336
      - name: transactions_1555
      - name: transactions_1581
      - name: transactions_1587
      - name: transactions_1831
      - name: transactions_1843
      - name: transactions_2066
      - name: tree_608
      - name: triangle_610
      - name: trips_262
      - name: tv_program_1495
      - name: tweets_1683
      - name: unit_sold_1251
      - name: user_activity_1369
      - name: user_visits_1709
      - name: users_1158
      - name: users_1159
      - name: users_1341
      - name: users_1407
      - name: users_1517
      - name: users_1555
      - name: users_1587
      - name: users_1633
      - name: users_1667
      - name: users_1811
      - name: users_262
      - name: variables_1440
      - name: views_1148
      - name: views_1149
      - name: visits_1336
      - name: visits_1581
      - name: visits_2051
      - name: vote_574
      - name: warehouse_1571
      - name: weather_1294
      - name: weather_197
      - name: weather_2314
      - name: world_595
      - name: my_first_dbt_model
